apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: prometheus-webhook
  namespace: argo-events
spec:
  webhook:
    prometheus:
      port: 12000
      endpoint: /alerts
      method: POST
