# k3s-homelab/infrastructure/cluster/manifests/shared-storage/shared-data-pvc-jupyterhub.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-data-pvc # This name will be referenced in JupyterHub's extraVolumes
  namespace: jupyterhub # MUST be in the jupyterhub namespace
spec:
  accessModes:
    - ReadWriteMany # Allows multiple pods to read and write concurrently
  resources:
    requests:
      storage: 500Gi # Generous size for all project data (raw, processed)
  storageClassName: nfs-shared # Must match your configured NFS StorageClass