---
- name: Create MLflow namespace
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ mlflow_namespace }}"

- name: Create MLflow PVC
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    definition: "{{ lookup('template', 'pvc.yaml.j2') | from_yaml }}"

- name: Deploy MLflow
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    definition: "{{ lookup('template', 'deployment.yaml.j2') | from_yaml }}"

- name: Create MLflow Service
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    definition: "{{ lookup('template', 'service.yaml.j2') | from_yaml }}"