---
galaxy_info:
  role_name: k3s_control_plane
  author: Your Name
  description: Deploy and manage K3s Kubernetes control plane
  license: MIT
  min_ansible_version: "2.12"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: Debian
      versions:
        - bullseye
        - bookworm
  galaxy_tags:
    - kubernetes
    - k3s
    - containers
    - infrastructure

dependencies: []
