---
- name: Configure UFW for K3s cluster communication
  block:
    - name: Allow K3s API server (6443)
      community.general.ufw:
        rule: allow
        port: "6443"
        proto: tcp
        src: "{{ hostvars[item]['ansible_default_ipv4']['address'] }}"
      with_items: "{{ groups['all'] }}"
      when: hostvars[item]['ansible_default_ipv4']['address'] != ansible_default_ipv4.address

    - name: Allow Kubelet API (10250)
      community.general.ufw:
        rule: allow
        port: "10250"
        proto: tcp
        src: "{{ hostvars[item]['ansible_default_ipv4']['address'] }}"
      with_items: "{{ groups['all'] }}"
      when: hostvars[item]['ansible_default_ipv4']['address'] != ansible_default_ipv4.address

    - name: Allow Flannel VXLAN (8472)
      community.general.ufw:
        rule: allow
        port: "8472"
        proto: udp
        src: "{{ hostvars[item]['ansible_default_ipv4']['address'] }}"
      with_items: "{{ groups['all'] }}"
      when: hostvars[item]['ansible_default_ipv4']['address'] != ansible_default_ipv4.address

    - name: Allow Node Exporter (9100)
      community.general.ufw:
        rule: allow
        port: "9100"
        proto: tcp
        src: "{{ hostvars[item]['ansible_default_ipv4']['address'] }}"
      with_items: "{{ groups['all'] }}"
      when: hostvars[item]['ansible_default_ipv4']['address'] != ansible_default_ipv4.address

    - name: Allow NodePort range (30000-32767)
      community.general.ufw:
        rule: allow
        port: "30000:32767"
        proto: tcp
        comment: "K3s NodePort services"

    - name: Allow pod-to-pod communication (CNI)
      community.general.ufw:
        rule: allow
        src: "10.42.0.0/16"
        comment: "K3s pod network"

    - name: Allow service network
      community.general.ufw:
        rule: allow
        src: "10.43.0.0/16"
        comment: "K3s service network"

    - name: Reload UFW rules
      community.general.ufw:
        state: reloaded
  tags: [k3s, firewall, security]