---
# JupyterHub Configuration
jupyterhub_namespace: jupyterhub
jupyterhub_name: jupyterhub
jupyterhub_chart_ref: jupyterhub/jupyterhub

# Service Configuration
jupyterhub_nodeport: 30888
jupyterhub_service_type: NodePort

# Authentication Configuration
jupyterhub_auth_type: dummy
jupyterhub_password: mlops123

# User Environment Configuration
jupyterhub_image_name: jupyter/datascience-notebook
jupyterhub_image_tag: latest
jupyterhub_default_url: /lab

# Storage Configuration
jupyterhub_storage_type: none  # Use 'dynamic' for persistent storage
jupyterhub_storage_class: nfs-shared
jupyterhub_storage_size: 10Gi

# Resource Configuration (FIXED: Use numbers for CPU, strings for memory)
jupyterhub_hub_memory_request: 512Mi
jupyterhub_hub_memory_limit: 1Gi
jupyterhub_hub_cpu_request: 0.2      # ✅ Number: 200m = 0.2 cores
jupyterhub_hub_cpu_limit: 0.5        # ✅ Number: 500m = 0.5 cores

jupyterhub_user_memory_request: 1Gi
jupyterhub_user_memory_limit: 2Gi
jupyterhub_user_cpu_request: 0.1     # ✅ Number: 100m = 0.1 cores  
jupyterhub_user_cpu_limit: 1.0       # ✅ Number: 1000m = 1.0 cores

# Helm Configuration
helm_wait_timeout: 600s
helm_retries: 3
helm_retry_delay: 30