apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: prometheus-alert-sensor
  namespace: argo-events
spec:
  dependencies:
    - name: prometheus-alert
      eventSourceName: prometheus-webhook
      eventName: prometheus
  triggers:
    - template:
        name: argo-workflow-trigger
        argoWorkflow:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: triggered-workflow-
                namespace: argowf
              spec:
                entrypoint: whalesay
                templates:
                  - name: whalesay
                    container:
                      image: docker/whalesay
                      command: [cowsay]
                      args: ["This workflow was triggered by a Prometheus alert!"]
