---
- name: Deploy MinIO Credentials for MLflow
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    src: "{{ playbook_dir }}/../manifests/sealed-secrets/minio-secret-mlflow.yaml"
    state: present
  tags: [storage, credentials, mlflow]

- name: Deploy MinIO Credentials for Argo Workflows
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    src: "{{ playbook_dir }}/../manifests/sealed-secrets/minio-secret-wf.yaml"
    state: present
  tags: [storage, credentials, argo]

- name: Deploy MinIO Credentials for Kubeflow
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    src: "{{ playbook_dir }}/../manifests/sealed-secrets/minio-secret-kubeflow.yaml"
    state: present
  failed_when: false
  tags: [storage, credentials, kubeflow]

- name: Verify credentials deployment
  debug:
    msg:
      - "✅ Storage credentials deployed"
      - "🔑 MLflow, Argo, and Kubeflow MinIO secrets available"
  tags: [storage, summary]