---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgA/Dgo6HgQ+gOJHr94mw0bBQctHS9RXzUus/J7lMt15Sk31m1ZB+X0QuLXA4HKMb+BgY9OZaue7n9lts57cx8GOVMRU52z5zEFvuHtdUbJ8N513T0yRA6fmreQeP1mshfkcCp34vItz34NrknzfDYZugEkL3ocMpwGnORmFN4awCpk1FtUGiaPBI3oJ7X65DK3proZdK0Gh7dG9j7fFc9OtP2Ferp95f9zfZS2zCAot1Y/iPcs98psiU+3LQ/nEOTPtr81ktI/YTRB2CJfrfA4y4hpvpjaDBBv68mTDgBtIv6pJB8cu85niAs7AU+8paIlF9+FkIW12cqpgZyqi90sgAL9Wb6uS66dFz2jTyXs+YssKirMf2xIbZrNZTq+WVy2VtNdLW0a7v8CR/LpLNGRa2xlwnCWQtVRsCZLL9rby2R8Yby9BwiGIxO6sBT6FJuzWpBWU2SGEkR5YehfNNy67OnNnAtR9ssEJLypZBOkjP1rK9+M/jEOyKP+zYPrf1w0LBKgVWp1REmN0U+koTa2ap4kwl6/L7bKLhwfKvmgT+CiKu/eozEgsCuFzdzicspeF/au7xNoGOaEtZPeGJWDHLqV47t/nOrR34y/eZg/AWTkT0CtkC0lwAfSShxZH9lCFsHND+FsrLbUIvz9UsxED+MrJHagPUnSIPiYM1DxnkIkfAT6YzNvK2c4bN9kLjN0I+2ktjGfL+g==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-secret
      namespace: monitoring
