---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-credentials
  namespace: minio
spec:
  encryptedData:
    access-key: AgB2pTwGu9hlB2RYeUbpadWTWu1ozpn0ZG+4jA0/KXFXzBeCwcKwCSkUy5YSBxA2ArhVk1PYQtRN3DMkXgPcNqV1G9MpugkgXL8TLL3iS1YnMQIcylKBUcQT2i90tygvU3CdMpTKBVANeg9fIrKlqtaIl+s1QL77Moidpy96cMY6Yu30fpUyZKYXHM+E3bXlymggB2cLz03xluEBpaDA2n//Y9Bc1+fyDY4GeDEpX3AvfW23OD76GrWgyf7tOYe77bgOtk+fseMIEneZOO5LjjSXTH/y+wl4VHhjfPIGReMTIsoQ2GlkzFafUAWQz5Dzl93C5drVoQByKY6bi+jcvP3lAFR1r9Xq7vlK+8EfrDk4C+AkKQ4WrlCgqIffiCOfO1VprcdeeOzXycQc1ay9ZgzD6xrukrkq7+3pKAvSiKLPvAVScY1ShKjKGfKBaco++0BKdo+8q0oOkHxNkJ4f1Atcu979TIFtCHsyG+uiui2P/wlMgz7ZfuQEa7tl7Qz7HKli8BwqzIG5LGCM/fGfMXjmNwpeMYlEhKbBTN8YGiPX1jdR+fRquE+R6CczND5EPrDmEiUo7/PDRHEmLsZZuXuu/D2zACY/JnfChT+1o/d6c5ckbg7Y0HnTfETRWoqh9WJx1ffuDAJM8tTGyjfcqEXAqsUrH5WoZfH5HaADS8RG+spk+BsSVWALB+nf0otuT7rWmJtL4tNKPy6E
    secret-key: AgBrb+CTleegHw9Af7o0YO0IgjBsCOd4kTOkkvfX3V9ihrB65qXa6QSpqWvO1+JyJrnny9XspAZkiKxqBSdrHRnRrdBRElLRhm2fr1rtbPCtii/H8s6bjCqM0lHd9z+nd/uarL7U0pULanV7XTGbgnNcoVKIEAEnJj4B1xj/rEBu8e496PUU5a1INwqmF/AD2glCvQf30bC9NySlQXeEaSGh6yUtjDpMH4AgNMUCCNWRmTZEzGEZ8eSveoHMuD/4U6AR4cnBa65kPn86xAEmBhsjVXUsdWqA+4rLWpfpXoTS1kIztGEzaiQ4wSd8Ubah02IcUqscCrq6/taPyik4HR5MaQW7nLEZuPq08LJpFUFYRMZDhaWI/kBNGORxefhd5QgXalFM0oXzDOqz8l+YuCeY/Nd4DbVE5CpPP7K76jvfaUTMpik+Gp30Q3QAyc7HT4lFKNKBDnnCCscHoAs25/mMxQZjVuSSScXRHEKR04BLHnH1ktuuYK+zd9NPX8yfUIavwxACnML21u2pD4qjL+CrjgqZdPuykk0cyeJD3/CwYoUI6gj1Rf9AvZ7L7UKG08fiC/QaFY2+KxQFk6B5uQ6Bg/Wa6wQiwsdbWXLmcsWXcpjroCR+4ztXZUZnAyVM3YimoTebUkJXKbAHtXsG1l/ahaEnOv/Epsft04ErIUPARhj78cVe3SxFldpRdFOkZcA4MnfgNNdl1otvSGDc
  template:
    metadata:
      creationTimestamp: null
      name: minio-credentials
      namespace: minio
