---
# Prometheus Stack Configuration
prometheus_stack_namespace: monitoring
prometheus_stack_name: prometheus-stack
prometheus_stack_chart_ref: prometheus-community/kube-prometheus-stack

# Grafana Configuration
grafana_nodeport: 30300
grafana_admin_password: admin123

# Prometheus Configuration  
prometheus_nodeport: 30090
prometheus_storage_size: 20Gi
prometheus_storage_class: nfs-shared

# Resource Configuration
prometheus_memory_request: 1Gi
prometheus_memory_limit: 4Gi
prometheus_cpu_request: 200m
prometheus_cpu_limit: 1000m

grafana_memory_request: 128Mi
grafana_memory_limit: 1Gi
grafana_cpu_request: 100m
grafana_cpu_limit: 500m

# Helm Configuration
helm_wait_timeout: 600s
helm_retries: 3
helm_retry_delay: 30

# Prometheus Pushgateway Configuration
pushgateway_nodeport: 32091
pushgateway_memory_request: 64Mi
pushgateway_memory_limit: 256Mi
pushgateway_cpu_request: 50m
pushgateway_cpu_limit: 200m