---
- name: Create K3s directories
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  loop:
    - "{{ k3s_config_dir }}"
    - "{{ k3s_data_dir }}"

- name: Download K3s installer
  get_url:
    url: "{{ k3s_install_script_url }}"
    dest: "/tmp/k3s-install.sh"
    mode: '0755'
  register: k3s_installer

- name: Install K3s control plane
  shell: |
    INSTALL_K3S_VERSION="{{ k3s_version }}" \
    INSTALL_K3S_CHANNEL="{{ k3s_channel }}" \
    INSTALL_K3S_EXEC="server {{ k3s_server_args | join(' ') }}" \
    /tmp/k3s-install.sh
  environment:
    K3S_CLUSTER_SECRET: "{{ k3s_cluster_secret | default(omit) }}"
  notify:
    - restart k3s
    - wait for k3s

- name: Enable and start K3s service
  systemd:
    name: k3s
    enabled: true
    state: started
    daemon_reload: true